Create Failed Experiment Metadata

diff --git a/.github/workflows/sgd-test.yml b/.github/workflows/sgd-test.yml
--- a/.github/workflows/sgd-test.yml
+++ b/.github/workflows/sgd-test.yml
@@ -203,3 +203,8 @@ jobs:
           echo "=============================="
 
           cat delta/package/package.xml
+
+      - name: Intentional Failure
+        run: |
+          echo "Intentional failure"
+          exit 1
