Create Failed SGD Experiment Run

diff --git a/.github/workflows/sgd-test.yml b/.github/workflows/sgd-test.yml
--- a/.github/workflows/sgd-test.yml
+++ b/.github/workflows/sgd-test.yml
@@ -153,3 +153,8 @@ jobs:
           echo "=============================="
 
           cat delta/package/package.xml
+
+      - name: INTENTIONAL FAILURE
+        run: |
+          echo "This run is intentionally failing for the SGD Experiment"
+          exit 1
